FROM phusion/baseimage:latest
MAINTAINER Seven Zhang <galaxywork@qq.com>

CMD ["/sbin/my_init"]


# ...put your own build instructions here...

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*